# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 500e0469da8c4e152b8fb67d56fade2ba9c9685df4e631144aaa1c7cae9a627061bcd2f6ba35f7a97395c6fa9b0d63c5edf9ba45be161f9e3d9381a23300285d

test:
  secret_key_base: fbb6a1db8422baeb40badc05d40d3294347c119d43754f94bb838f3a4c51c94c0bc5c4fe00ab1fb827ceb0e45139b5d992fdd4871659e787b9d55c31cc446757

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>